version: '3'

services:
  shopping_web:
    build:
      context: docker/local/web
      dockerfile: Dockerfile
      args:
        - WWW_DATA_USER=${WWW_DATA_USER:-1001}
        - WWW_DATA_GROUP=${WWW_DATA_GROUP:-1001}
        - ENVIRONMENT=${APP_ENV:-local}
    container_name: shopping_web
    env_file:
        - .env
    ports:
      - "${WEP_PORT:-8081}:80"
    volumes:
      - ./:/var/www/
      - ./docker/local/web/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/local/web/site.conf:/etc/nginx/sites-enabled/site.conf
    depends_on:
      - shopping_php

  shopping_php:
    build:
      context: docker/local/php
      dockerfile: Dockerfile
      args:
        - WWW_DATA_USER=${WWW_DATA_USER:-1001}
        - WWW_DATA_GROUP=${WWW_DATA_GROUP:-1001}
        - ENVIRONMENT=${APP_ENV:-local}
    container_name: shopping_php
    env_file:
        - .env
    expose:
      - "9000"
    environment:
      - WWW_DATA_USER=${WWW_DATA_USER:-1001}
    volumes:
      - ./:/var/www/
      - ./docker/local/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/local/php/php_debug.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/local/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/local/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - shopping_mysql

  shopping_mysql:
    image: mysql:8.0.22
    container_name: shopping_mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-shopping}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-123456}
      - MYSQL_USER=${DB_USERNAME:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-123456}
    ports:
      - "${DB_MYSQL_PORT:-3308}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  shopping_phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    container_name: shopping_phpmyadmin
    depends_on:
      - shopping_mysql
    ports:
      - "${DB_MYSQL_PORT:-8082}:80"
    environment:
      - PMA_HOST=shopping_mysql
